import { Exercise } from "../types/Exercise";

export const MURPH_WORKOUT_TEMPLATE: Exercise[] = [
  {
    name: "Running 1",
    unit: "km",
    taskAmount: 1.6,
    repetitionIncrement: [],
    goalValueInSeconds: null,
    startTimestamp: null,
    endTimestamp: null,
    details: [],
  },
  {
    name: "Push-ups",
    unit: "rep",
    taskAmount: 100,
    repetitionIncrement: [3, 4, 5, 10],
    goalValueInSeconds: null,
    startTimestamp: null,
    endTimestamp: null,
    details: [],
  },
  {
    name: "Pull-ups",
    unit: "rep",
    taskAmount: 200,
    repetitionIncrement: [5, 10, 20],
    goalValueInSeconds: null,
    startTimestamp: null,
    endTimestamp: null,
    details: [],
  },
  {
    name: "Squats",
    unit: "rep",
    taskAmount: 300,
    repetitionIncrement: [10, 20, 30],
    goalValueInSeconds: null,
    startTimestamp: null,
    endTimestamp: null,
    details: [],
  },
  {
    name: "Running 2",
    unit: "km",
    taskAmount: 1.6,
    repetitionIncrement: [],
    goalValueInSeconds: null,
    startTimestamp: null,
    endTimestamp: null,
    details: [],
  },
];
